services:
  vllm:
    build:
      context: ./service/vllm
      args:
        - VLLM_VERSION=${VLLM_VERSION}
    ports:
      - "${BIND_ADDRESS}${BIND_COLON}${VLLM_PORT}:8000"
    entrypoint: bash /etc/vllm/entrypoint.sh
    volumes:
      - ${MODEL_DIR}:/data/models
      - ./service/vllm/etc/config.yaml:/etc/vllm/config.yaml
      - ./service/vllm/etc/entrypoint.sh:/etc/vllm/entrypoint.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "0" ]
              capabilities: [ "gpu" ]
  sglang:
    build:
      context: ./service/sglang
      args:
        - SGLANG_VERSION=${SGLANG_VERSION}
    ports:
      - "${BIND_ADDRESS}${BIND_COLON}${SGLANG_PORT}:30000"
    entrypoint: bash /etc/sglang/entrypoint.sh
    volumes:
      - ${MODEL_DIR}:/data/models
      - ./service/sglang/etc/config.yaml:/etc/sglang/config.yaml
      - ./service/sglang/etc/entrypoint.sh:/etc/sglang/entrypoint.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [ "gpu" ]
