wiki:
  filepath: data/wiki.jsonl
  text_field: content

news:
  filepath: data/news.jsonl
  text_field: content

identity:
  filepath: data/identity.jsonl
  input_field: input
  output_field: output

rlhf:
  filepath: data/rlhf.jsonl
  prompt_field: prompt
  chosen_field: chosen
  rejected_field: rejected
