version: 1
disable_existing_loggers: False
formatters:
  default:
    "()": "uvicorn.logging.DefaultFormatter"
    fmt: "%(asctime)s - %(levelprefix)s %(message)s"
    use_colors: False
  access:
    "()": "uvicorn.logging.AccessFormatter"
    fmt: '%(asctime)s - %(levelprefix)s %(client_addr)s - "%(request_line)s" %(status_code)s'
    use_colors: False
handlers:
  default:
    formatter: "default"
    class: "logging.StreamHandler"
    stream: "ext://sys.stderr"
  access:
    formatter: "default"
    class: "logging.StreamHandler"
    stream: "ext://sys.stdout"
  access_file:
    class: "logging.handlers.TimedRotatingFileHandler"
    formatter: "access"
    filename: "./logs/uvicorn.access.log"
    when: "midnight"
    interval: 1
    backupCount: 7
    encoding: "utf-8"
  error_file:
    class: "logging.handlers.TimedRotatingFileHandler"
    formatter: "default"
    filename: "./logs/uvicorn.error.log"
    when: "midnight"
    interval: 1
    backupCount: 7
    encoding: "utf-8"
loggers:
  uvicorn.access:
    level: "INFO"
    handlers: [ "access", "access_file" ]
    propagate: False
  uvicorn.error:
    level: "INFO"
    handlers: [ "default", "error_file" ]
    propagate: False
