action: train
model_name_or_path: models/Qwen2.5-0.5B-Instruct

stage: rlhf
fine_tuning: lora
deepspeed: config/ds_z3_config.json

train_dataset_names: rlhf
eval_dataset_names: rlhf
max_steps: 30
learning_rate: 1.0e-4

output_dir: models/qwen-rlhf-lora
